export type Product = {
  id: string;
  name: string;
  category: "Signature" | "Klasik" | "Non-Kopi" | "Makanan" | "Camilan";
  price: number;
  rating: number;
  description: string;
  icon: string;
  imageUrl?: string;
};

export const categories = ["Semua", "Signature", "Klasik", "Non-Kopi", "Makanan", "Camilan"] as const;

export const products: Product[] = [
  // ============================================
  // SIGNATURE - Special menu dengan racikan unik
  // ============================================
  {
    id: "sig-01",
    name: "Aroma Gula Aren",
    category: "Signature",
    price: 25000,
    rating: 4.8,
    description: "Espresso, susu segar, gula aren rumahan. Racikan signature yang jadi favorit.",
    icon: "☕",
  },
  {
    id: "sig-02",
    name: "Espresso Romance",
    category: "Signature",
    price: 28000,
    rating: 4.9,
    description: "Double espresso, vanilla syrup, steamed milk. Romantic vibes in a cup.",
    icon: "💝",
  },
  {
    id: "sig-03",
    name: "Hazelnut Latte",
    category: "Signature",
    price: 27000,
    rating: 4.7,
    description: "Espresso, hazelnut syrup, susu-microfoam. Nutty & creamy perfection.",
    icon: "🌰",
  },
  {
    id: "sig-04",
    name: "Caramel Macchiato",
    category: "Signature",
    price: 29000,
    rating: 4.8,
    description: "Vanilla, espresso, caramel drizzle, steamed milk. Sweet indulgence.",
    icon: "🍯",
  },
  {
    id: "sig-05",
    name: "Affogato Coffee",
    category: "Signature",
    price: 32000,
    rating: 4.9,
    description: "Espresso shot di atas vanilla ice cream. Dessert meets coffee.",
    icon: "🍨",
  },
  {
    id: "sig-06",
    name: "Kopi Tubruk Aroma",
    category: "Signature",
    price: 17000,
    rating: 4.4,
    description: "Cara seduh tradisional, kopi robusta pilihan. Authentic Indonesian taste.",
    icon: "🫘",
  },
  {
    id: "sig-07",
    name: "Vietnamese Drip",
    category: "Signature",
    price: 23000,
    rating: 4.6,
    description: "Kopi Vietnamese style, susu condensed, es batu. Bold & sweet.",
    icon: "☕",
  },
  {
    id: "sig-08",
    name: "Butter Coffee",
    category: "Signature",
    price: 26000,
    rating: 4.5,
    description: "Kopi butter blend, creamy texture. Energi tahan lama.",
    icon: "🧈",
  },
  {
    id: "sig-09",
    name: "Oreo Latte",
    category: "Signature",
    price: 28000,
    rating: 4.7,
    description: "Espresso, susu, remukan Oreo. Crunchy sweetness in every sip.",
    icon: "🥛",
  },
  {
    id: "sig-10",
    name: "Palm Sugar Latte",
    category: "Signature",
    price: 25000,
    rating: 4.6,
    description: "Espresso, susu, gula aren asli. Natural sweetness, Indonesian twist.",
    icon: "🌴",
  },
  {
    id: "sig-11",
    name: "Tiramisu Latte",
    category: "Signature",
    price: 30000,
    rating: 4.9,
    description: "Espresso, mascarpone, cocoa powder. Like dessert in a cup.",
    icon: "🍰",
  },
  {
    id: "sig-12",
    name: "Salt Caramel Latte",
    category: "Signature",
    price: 29000,
    rating: 4.8,
    description: "Espresso, caramel garam, steamed milk. Sweet-salty heaven.",
    icon: "🧂",
  },
  {
    id: "sig-13",
    name: "Brown Sugar Boba Latte",
    category: "Signature",
    price: 28000,
    rating: 4.7,
    description: "Espresso, susu, boba gula aren. Trending & delicious.",
    icon: "🧋",
  },
  {
    id: "sig-14",
    name: "Dirty Coffee",
    category: "Signature",
    price: 22000,
    rating: 4.5,
    description: "Espresso shot di atas susu dingin. Layered perfection.",
    icon: "💧",
  },
  {
    id: "sig-15",
    name: "Hazzelbrew Delight",
    category: "Signature",
    price: 31000,
    rating: 4.8,
    description: "Hazelnut, chocolate, espresso blend. Our house special.",
    icon: "✨",
  },

  // ============================================
  // KLASIK - Kopi klasik yang always in style
  // ============================================
  {
    id: "cla-01",
    name: "Kopi Susu Klasik",
    category: "Klasik",
    price: 20000,
    rating: 4.6,
    description: "Racikan sederhana yang selalu jadi favorit. Kenyal & creamy.",
    icon: "🥛",
  },
  {
    id: "cla-02",
    name: "Americano Dingin",
    category: "Klasik",
    price: 18000,
    rating: 4.5,
    description: "Espresso double shot, air dingin, tanpa gula. Clean & bold.",
    icon: "🧊",
  },
  {
    id: "cla-03",
    name: "Cappuccino",
    category: "Klasik",
    price: 22000,
    rating: 4.6,
    description: "Espresso, steamed milk, milk foam. Italian classic.",
    icon: "🥤",
  },
  {
    id: "cla-04",
    name: "Cafe Latte",
    category: "Klasik",
    price: 23000,
    rating: 4.7,
    description: "Espresso, susu steamed, foam tipis. Smooth & milky.",
    icon: "🍶",
  },
  {
    id: "cla-05",
    name: "Espresso Shot",
    category: "Klasik",
    price: 15000,
    rating: 4.3,
    description: "Single shot espresso. Bold, strong, no nonsense.",
    icon: "⚡",
  },
  {
    id: "cla-06",
    name: "Long Black",
    category: "Klasik",
    price: 19000,
    rating: 4.4,
    description: "Double espresso, air panas, crema tebal. Aussie style.",
    icon: "🖤",
  },
  {
    id: "cla-07",
    name: "Kopi Hitam",
    category: "Klasik",
    price: 16000,
    rating: 4.2,
    description: "Kopi tubruk pure, pahit authentic. traditional vibes.",
    icon: "🪵",
  },
  {
    id: "cla-08",
    name: "Double Espresso",
    category: "Klasik",
    price: 20000,
    rating: 4.4,
    description: "Two shots of pure espresso. Maximum caffeine.",
    icon: "💪",
  },
  {
    id: "cla-09",
    name: "Flat White",
    category: "Klasik",
    price: 24000,
    rating: 4.7,
    description: "Double shot, susu steamed microfoam. Velvety smooth.",
    icon: "☁️",
  },
  {
    id: "cla-10",
    name: "Cortado",
    category: "Klasik",
    price: 21000,
    rating: 4.5,
    description: "Espresso, sedikit susu. Balanced & smooth.",
    icon: "🎯",
  },
  {
    id: "cla-11",
    name: "Gibraltar",
    category: "Klasik",
    price: 23000,
    rating: 4.6,
    description: "Double shot, susu steamed. San Francisco classic.",
    icon: "🏔️",
  },
  {
    id: "cla-12",
    name: "Mochaccino",
    category: "Klasik",
    price: 25000,
    rating: 4.6,
    description: "Espresso, chocolate, steamed milk. Chocolate coffee combo.",
    icon: "🍫",
  },
  {
    id: "cla-13",
    name: "Irish Coffee",
    category: "Klasik",
    price: 35000,
    rating: 4.8,
    description: "Espresso, Irish cream, whipped cream. Sophisticated treat.",
    icon: "🍀",
  },
  {
    id: "cla-14",
    name: "Turkish Coffee",
    category: "Klasik",
    price: 22000,
    rating: 4.5,
    description: "Seduh Turkish style, fine grind. Strong & aromatic.",
    icon: "🏺",
  },
  {
    id: "cla-15",
    name: "Iced Americano",
    category: "Klasik",
    price: 20000,
    rating: 4.4,
    description: "Espresso, air es, tanpa susu. Refreshing & bold.",
    icon: "🧋",
  },
  {
    id: "cla-16",
    name: "Black Eye Coffee",
    category: "Klasik",
    price: 22000,
    rating: 4.5,
    description: "Double espresso di atas drip coffee. Maximum boost.",
    icon: "👁️",
  },
  {
    id: "cla-17",
    name: "Red Eye Coffee",
    category: "Klasik",
    price: 24000,
    rating: 4.6,
    description: "Triple shot espresso di atas drip. For serious caffeine lovers.",
    icon: "🔴",
  },

  // ============================================
  // NON-KOPI - Untuk yang nggak mau kopi
  // ============================================
  {
    id: "non-01",
    name: "Matcha Latte",
    category: "Non-Kopi",
    price: 23000,
    rating: 4.7,
    description: "Matcha grade ceremonial, susu creamy. Japanese green tea vibes.",
    icon: "🍵",
  },
  {
    id: "non-02",
    name: "Taro Latte",
    category: "Non-Kopi",
    price: 24000,
    rating: 4.6,
    description: "Taro paste, susu segar, creamy texture. Purple perfection.",
    icon: "🟣",
  },
  {
    id: "non-03",
    name: "Chocolate Lava",
    category: "Non-Kopi",
    price: 25000,
    rating: 4.8,
    description: "Belgian chocolate, steamed milk, whipped cream. Rich & decadent.",
    icon: "🍫",
  },
  {
    id: "non-04",
    name: "Red Velvet Latte",
    category: "Non-Kopi",
    price: 24000,
    rating: 4.5,
    description: "Red velvet syrup, susu, cream cheese topping. Elegant & sweet.",
    icon: "❤️",
  },
  {
    id: "non-05",
    name: "Fresh Orange Juice",
    category: "Non-Kopi",
    price: 20000,
    rating: 4.4,
    description: "Jeruk peras segar, no added sugar. Pure & refreshing.",
    icon: "🍊",
  },
  {
    id: "non-06",
    name: "Lychee Tea",
    category: "Non-Kopi",
    price: 18000,
    rating: 4.3,
    description: "Teh melati, sirup lychee, strawberry slice. Floral & fruity.",
    icon: "🫧",
  },
  {
    id: "non-07",
    name: "Mango Smoothie",
    category: "Non-Kopi",
    price: 26000,
    rating: 4.7,
    description: "Mango pilihan, yogurt, madu. Tropical paradise in a cup.",
    icon: "🥭",
  },
  {
    id: "non-08",
    name: "Strawberry Milkshake",
    category: "Non-Kopi",
    price: 25000,
    rating: 4.6,
    description: "Strawberry segar, ice cream vanilla, susu. Sweet & creamy.",
    icon: "🍓",
  },
  {
    id: "non-09",
    name: "Chocolate Milkshake",
    category: "Non-Kopi",
    price: 25000,
    rating: 4.7,
    description: "Chocolate syrup, ice cream, susu. Classic comfort drink.",
    icon: "🍫",
  },
  {
    id: "non-10",
    name: "Avocado Shake",
    category: "Non-Kopi",
    price: 24000,
    rating: 4.5,
    description: "Alpukat matang, susu, madu. Creamy & nutritious.",
    icon: "🥑",
  },
  {
    id: "non-11",
    name: "Lemon Tea",
    category: "Non-Kopi",
    price: 15000,
    rating: 4.2,
    description: "Teh segar, perasan lemon, es batu. Simple & refreshing.",
    icon: "🍋",
  },
  {
    id: "non-12",
    name: "Ice Thai Tea",
    category: "Non-Kopi",
    price: 18000,
    rating: 4.4,
    description: "Teh Thailand, susu, es batu. Sweet & creamy Thai style.",
    icon: "🧋",
  },
  {
    id: "non-13",
    name: "Green Tea Latte",
    category: "Non-Kopi",
    price: 22000,
    rating: 4.5,
    description: "Green tea, susu, less sugar option. Light & healthy.",
    icon: "🍵",
  },
  {
    id: "non-14",
    name: "Yakult Soda",
    category: "Non-Kopi",
    price: 15000,
    rating: 4.3,
    description: "Yakult, soda, es batu. Probiotic refreshment.",
    icon: "🥤",
  },
  {
    id: "non-15",
    name: "Es Krim Soda",
    category: "Non-Kopi",
    price: 20000,
    rating: 4.5,
    description: "Soda, ice cream scoop, syrup pilihan. Fun & fizzy.",
    icon: "🍦",
  },
  {
    id: "non-16",
    name: "Coconut Water",
    category: "Non-Kopi",
    price: 18000,
    rating: 4.2,
    description: "Air kelapa segar, es batu. Natural hydration.",
    icon: "🥥",
  },
  {
    id: "non-17",
    name: "Watermelon Juice",
    category: "Non-Kopi",
    price: 22000,
    rating: 4.4,
    description: "Semangka segar, no added sugar. Summer vibes.",
    icon: "🍉",
  },
  {
    id: "non-18",
    name: "Pineapple Smoothie",
    category: "Non-Kopi",
    price: 24000,
    rating: 4.5,
    description: "Nanas segar, yogurt, madu. Tropical tangy goodness.",
    icon: "🍍",
  },
  {
    id: "non-19",
    name: "Banana Shake",
    category: "Non-Kopi",
    price: 22000,
    rating: 4.4,
    description: "Pisang matang, susu, madu. Energy boost smoothie.",
    icon: "🍌",
  },
  {
    id: "non-20",
    name: "Berry Blast Smoothie",
    category: "Non-Kopi",
    price: 28000,
    rating: 4.7,
    description: "Mixed berries, yogurt, honey. Antioxidant packed.",
    icon: "🫐",
  },

  // ============================================
  // MAKANAN - Makanan berat & rice bowl
  // ============================================
  {
    id: "food-01",
    name: "Nasi Goreng Special",
    category: "Makanan",
    price: 35000,
    rating: 4.7,
    description: "Nasi goreng dengan telur, ayam suwir, kerupuk. Comfort food ultimate.",
    icon: "🍳",
  },
  {
    id: "food-02",
    name: "Ayam Geprek",
    category: "Makanan",
    price: 32000,
    rating: 4.6,
    description: "Ayam crispy, sambal bawang, nasi putih. Pedas bikin nagih.",
    icon: "🍗",
  },
  {
    id: "food-03",
    name: "Rice Bowl Teriyaki",
    category: "Makanan",
    price: 38000,
    rating: 4.8,
    description: "Ayam teriyaki, nasi, sayuran. Japanese vibes.",
    icon: "🍱",
  },
  {
    id: "food-04",
    name: "Mie Goreng Jawa",
    category: "Makanan",
    price: 30000,
    rating: 4.5,
    description: "Mie goreng style Jawa, telur, sayur. Authentic taste.",
    icon: "🍝",
  },
  {
    id: "food-05",
    name: "Chicken Katsu Curry",
    category: "Makanan",
    price: 42000,
    rating: 4.8,
    description: "Ayam katsu, kuah kari Jepang, nasi. Crispy & saucy.",
    icon: "🥘",
  },
  {
    id: "food-06",
    name: "Spaghetti Aglio Olio",
    category: "Makanan",
    price: 35000,
    rating: 4.6,
    description: "Pasta, garlic, olive oil, chili flakes. Italian simplicity.",
    icon: "🍝",
  },
  {
    id: "food-07",
    name: "Indomie Goreng Spesial",
    category: "Makanan",
    price: 25000,
    rating: 4.4,
    description: "Indomie goreng dengan telur, sosis, kerupuk. Indonesian comfort.",
    icon: "🍜",
  },
  {
    id: "food-08",
    name: "Rice Bowl BBQ",
    category: "Makanan",
    price: 40000,
    rating: 4.7,
    description: "Ayam BBQ sauce, nasi, coleslaw. Smoky goodness.",
    icon: "🥩",
  },
  {
    id: "food-09",
    name: "Ayam Bakar Madu",
    category: "Makanan",
    price: 38000,
    rating: 4.8,
    description: "Ayam bakar bumbu madu, nasi, lalapan. Sweet & savory.",
    icon: "🍗",
  },
  {
    id: "food-10",
    name: "Spaghetti Carbonara",
    category: "Makanan",
    price: 38000,
    rating: 4.7,
    description: "Pasta, egg, parmesan, bacon. Creamy Italian classic.",
    icon: "🍝",
  },
  {
    id: "food-11",
    name: "Tomyam Rice",
    category: "Makanan",
    price: 36000,
    rating: 4.6,
    description: "Nasi dengan kuah tomyam, seafood mix. Spicy Thai vibes.",
    icon: "🍲",
  },
  {
    id: "food-12",
    name: "Chicken Salted Egg",
    category: "Makanan",
    price: 40000,
    rating: 4.9,
    description: "Ayam crispy, saus salted egg, nasi. Trending & delicious.",
    icon: "🥚",
  },
  {
    id: "food-13",
    name: "Rice Bowl Blackpepper",
    category: "Makanan",
    price: 38000,
    rating: 4.6,
    description: "Ayam blackpepper, nasi, sayuran. Savory & spicy.",
    icon: "🥡",
  },
  {
    id: "food-14",
    name: "Bubur Ayam",
    category: "Makanan",
    price: 25000,
    rating: 4.5,
    description: "Bubur nasi, ayam suwir, cakwe, kecap. Breakfast comfort.",
    icon: "🥣",
  },
  {
    id: "food-15",
    name: "Lontong Sayur",
    category: "Makanan",
    price: 28000,
    rating: 4.4,
    description: "Lontong, sayur nangka, sambal, kerupuk. Betawi style.",
    icon: "🍛",
  },

  // ============================================
  // CAMILAN - Snack & kue
  // ============================================
  {
    id: "snack-01",
    name: "Croissant Almond",
    category: "Camilan",
    price: 22000,
    rating: 4.9,
    description: "Dipanggang tiap pagi, isian almond cream. Flaky perfection.",
    icon: "🥐",
  },
  {
    id: "snack-02",
    name: "Banana Nut Bread",
    category: "Camilan",
    price: 18000,
    rating: 4.6,
    description: "Banana cake moist, topping kacang walnut. Soft & nutty.",
    icon: "🍌",
  },
  {
    id: "snack-03",
    name: "Blueberry Muffin",
    category: "Camilan",
    price: 20000,
    rating: 4.7,
    description: "Muffin fluffy, blueberry segar imported. Bursting with berries.",
    icon: "🧁",
  },
  {
    id: "snack-04",
    name: "Chocolate Chip Cookie",
    category: "Camilan",
    price: 15000,
    rating: 4.5,
    description: "Freshly baked, chocolate chunk premium. Crispy edges, chewy center.",
    icon: "🍪",
  },
  {
    id: "snack-05",
    name: "Cheesecake Slice",
    category: "Camilan",
    price: 28000,
    rating: 4.9,
    description: "New York style, cream cheese, berry compote. Silky smooth.",
    icon: "🍰",
  },
  {
    id: "snack-06",
    name: "Pisang Goreng Keju",
    category: "Camilan",
    price: 16000,
    rating: 4.4,
    description: "Pisang crispy, topping keju mozzarella. Indonesian street food classic.",
    icon: "🍌",
  },
  {
    id: "snack-07",
    name: "French Fries",
    category: "Camilan",
    price: 18000,
    rating: 4.3,
    description: "Kentang crispy, saus pilihan (BBQ/sambal/mayo). Golden perfection.",
    icon: "🍟",
  },
  {
    id: "snack-08",
    name: "Chicken Wings",
    category: "Camilan",
    price: 28000,
    rating: 4.6,
    description: "Sayap ayam crispy, saus BBQ/sambal. Party snack essential.",
    icon: "🍗",
  },
  {
    id: "snack-09",
    name: "Croissant Chocolate",
    category: "Camilan",
    price: 20000,
    rating: 4.7,
    description: "Croissant dengan isian chocolate. Sweet breakfast option.",
    icon: "🥐",
  },
  {
    id: "snack-10",
    name: "Tartlet Buah",
    category: "Camilan",
    price: 25000,
    rating: 4.6,
    description: "Pastry shell, custard, fresh fruits. Light & fruity.",
    icon: "🥧",
  },
  {
    id: "snack-11",
    name: "Roti Bakar",
    category: "Camilan",
    price: 18000,
    rating: 4.4,
    description: "Roti panggang, selai pilihan (coklat/strawberry/keju). Simple comfort.",
    icon: "🍞",
  },
  {
    id: "snack-12",
    name: "Dimsum 6 Pcs",
    category: "Camilan",
    price: 32000,
    rating: 4.7,
    description: "Dimsum mix: hakau, siomay, hakka. Steamed fresh.",
    icon: "🥟",
  },
  {
    id: "snack-13",
    name: "Chicken Nuggets",
    category: "Camilan",
    price: 22000,
    rating: 4.3,
    description: "Nuggets ayam crispy, saus pilihan. Kids favorite.",
    icon: "🍗",
  },
  {
    id: "snack-14",
    name: "Onion Rings",
    category: "Camilan",
    price: 20000,
    rating: 4.4,
    description: "Bawang bombay crispy, saus ranch. Crunchy rings.",
    icon: "🧅",
  },
  {
    id: "snack-15",
    name: "Pancake Durian",
    category: "Camilan",
    price: 35000,
    rating: 4.9,
    description: "Pancake lembut, isian durian premium. King of fruits.",
    icon: "🥞",
  },
  {
    id: "snack-16",
    name: "Cireng",
    category: "Camilan",
    price: 15000,
    rating: 4.3,
    description: "Aci goreng crispy, saus rujak. Sundanese street food.",
    icon: "🍡",
  },
  {
    id: "snack-17",
    name: "Tahu Crispy",
    category: "Camilan",
    price: 12000,
    rating: 4.2,
    description: "Tahu goreng crispy, saus kecap sambal. Simple & addictive.",
    icon: "🧈",
  },
  {
    id: "snack-18",
    name: "Risoles",
    category: "Camilan",
    price: 18000,
    rating: 4.5,
    description: "Risoles renyah, isian ragut. Dutch-Indonesian heritage.",
    icon: "🥖",
  },
  {
    id: "snack-19",
    name: "Cinnamon Roll",
    category: "Camilan",
    price: 22000,
    rating: 4.7,
    description: "Roti gulung kayu manis, cream cheese frosting. Sweet aroma.",
    icon: "🌀",
  },
  {
    id: "snack-20",
    name: "Croffle",
    category: "Camilan",
    price: 25000,
    rating: 4.8,
    description: "Croissant waffle dengan topping pilihan. Trendy & crispy.",
    icon: "🧇",
  },
];

export function getRecommended(count = 3): Product[] {
  return [...products].sort((a, b) => b.rating - a.rating).slice(0, count);
}
